#!/usr/bin/env bash
# Clutch — Cursor cloud agent start (runs on each agent boot).
#  Cursor dashboard injects INFISICAL_CLIENT_ID / INFISICAL_CLIENT_SECRET.
#  This script:
#    * exports Infisical coordinates (PROJECT_ID / ENV / DOMAIN) into a
#      process-friendly env file under $HOME/.cursor-cloud-env/
#    * backfills the Clutch managed-key set so the CLI / tests can read
#      them through initClutchSettings
#    * sets CLUTCH_INFISICAL_ENV=dev for this cloud lane
#  It never prints secret values.  If credentials are missing it prints
#  the missing secret NAMES and exits 0 so the agent boot still succeeds.

set -euo pipefail

# Two ASCII spaces after periods and colons (fleet copy rule).
REPO_NAME="Clutch"
ENV_DIR="${HOME}/.cursor-cloud-env"
ENV_FILE="${ENV_DIR}/${REPO_NAME}.env"
SOURCE_FILE="${ENV_DIR}/${REPO_NAME}.source.sh"
INFISICAL_ENV_FILE=".cursor/infisical.env"
INTERNAL_TMP=""

log() { printf '[cursor-cloud-start] %s\n' "$*" >&2; }
cleanup() {
  if [[ -n "${INTERNAL_TMP}" && -e "${INTERNAL_TMP}" ]]; then
    rm -f "${INTERNAL_TMP}"
  fi
}
trap cleanup EXIT

mkdir -p "${ENV_DIR}"
chmod 700 "${ENV_DIR}"

# 1.  Always start from the committed, non-secret Infisical coordinates.
if [[ -f "${INFISICAL_ENV_FILE}" ]]; then
  # shellcheck disable=SC1090
  set -a; source "${INFISICAL_ENV_FILE}"; set +a
else
  log "WARN: ${INFISICAL_ENV_FILE} missing — using hard-coded coordinates"
  export INFISICAL_PROJECT_ID="077fd6f3-9f9b-438e-9b6f-5c69076cf36c"
  export INFISICAL_ENV="dev"
  export INFISICAL_DOMAIN="https://app.infisical.com"
fi

# 2.  Pin the lane the app's settings loader uses.
export CLUTCH_INFISICAL_ENV="${INFISICAL_ENV:-dev}"

# 3.  If dashboard credentials are missing, print NAMES only and exit 0.
missing=()
[[ -z "${INFISICAL_CLIENT_ID:-}"     ]] && missing+=("INFISICAL_CLIENT_ID")
[[ -z "${INFISICAL_CLIENT_SECRET:-}" ]] && missing+=("INFISICAL_CLIENT_SECRET")
if [[ ${#missing[@]} -gt 0 ]]; then
  log "missing Cursor dashboard secret(s): ${missing[*]}"
  log "ask Jay to add them under the team/org Cursor dashboard; agent boot continues without Infisical"
  printf '# Clutch — Cursor cloud env (no Infisical credentials present)\n' > "${ENV_FILE}"
  chmod 600 "${ENV_FILE}"
  cat > "${SOURCE_FILE}" <<EOF
# Source me: set -a; source "${ENV_FILE}"; set +a
if [ -f "${ENV_FILE}" ]; then
  set -a
  # shellcheck disable=SC1090
  . "${ENV_FILE}"
  set +a
fi
EOF
  chmod 600 "${SOURCE_FILE}"
  exit 0
fi

# 4.  Fetch the managed-key set from Infisical using universal auth.
#     We reuse the project's own runtime helper to keep the contract
#     identical with the Mac launcher.  See INFISICAL.md "Key inventory".
if ! command -v curl >/dev/null 2>&1 || ! command -v python3 >/dev/null 2>&1; then
  log "curl or python3 missing — cannot fetch Infisical secrets; agent boot continues"
  exit 0
fi

token="$(curl -s --max-time 15 -X POST "${INFISICAL_DOMAIN}/api/v1/auth/universal-auth/login" \
  -H 'Content-Type: application/json' \
  -d "{\"clientId\":\"${INFISICAL_CLIENT_ID}\",\"clientSecret\":\"${INFISICAL_CLIENT_SECRET}\"}" \
  | python3 -c 'import json,sys
try:
    print(json.load(sys.stdin).get("accessToken",""))
except Exception:
    pass
' 2>/dev/null || true)"
if [[ -z "${token}" ]]; then
  log "Infisical universal-auth login failed — agent boot continues"
  exit 0
fi

secrets_json="$(curl -s --max-time 20 \
  "${INFISICAL_DOMAIN}/api/v3/secrets/raw?workspaceId=${INFISICAL_PROJECT_ID}&environment=${INFISICAL_ENV}&secretPath=/" \
  -H "Authorization: Bearer ${token}" 2>/dev/null || true)"
token=""
if [[ -z "${secrets_json}" ]]; then
  log "Infisical secrets fetch failed — agent boot continues"
  exit 0
fi

# 5.  Build the env file from the managed-key set (matches
#     scripts/lib/clutch-infisical-env.sh and INFISICAL.md).
INTERNAL_TMP="$(mktemp -t clutch-cursor-cloud-env.XXXXXX)"
chmod 600 "${INTERNAL_TMP}"

CLUTCH_MANAGED_KEYS="MINIMAX_API_KEY DEEPSEEK_API_KEY CLUTCH_MINIMAX_API_KEY_NAME CLUTCH_MINIMAX_BASE_URL CLUTCH_MINIMAX_MODEL CLUTCH_MINIMAX_PROFILE CLUTCH_WEB_HOST CLUTCH_WEB_PORT CLUTCH_TAILNET_HOST CLUTCH_TAILNET_IPV4 CLUTCH_TRUSTED_HOSTS CLUTCH_SETTINGS_REFRESH_MS" \
python3 - "${secrets_json}" >"${INTERNAL_TMP}" <<'PY'
import json, os, shlex, sys
try:
    data = json.loads(sys.argv[1])
except Exception:
    sys.exit(2)
managed = os.environ.get("CLUTCH_MANAGED_KEYS", "").split()
values = {s.get("secretKey"): s.get("secretValue", "") for s in data.get("secrets", []) if s.get("secretKey")}
for key in managed:
    v = values.get(key)
    if v:
        print("export " + shlex.quote(key) + "=" + shlex.quote(v))
PY
write_status=$?
if [[ ${write_status} -ne 0 ]]; then
  log "Infisical response unparseable — agent boot continues"
  exit 0
fi

{
  printf '# Clutch — Cursor cloud env (Infisical backfill)\n'
  printf '# Generated by scripts/cursor-cloud-start.sh; do not edit by hand.\n'
  printf 'export INFISICAL_PROJECT_ID=%s\n' "$(python3 -c 'import shlex,sys; print(shlex.quote(sys.argv[1]))' "${INFISICAL_PROJECT_ID}")"
  printf 'export INFISICAL_ENV=%s\n'        "$(python3 -c 'import shlex,sys; print(shlex.quote(sys.argv[1]))' "${INFISICAL_ENV}")"
  printf 'export INFISICAL_DOMAIN=%s\n'     "$(python3 -c 'import shlex,sys; print(shlex.quote(sys.argv[1]))' "${INFISICAL_DOMAIN}")"
  printf 'export CLUTCH_INFISICAL_ENV=%s\n' "$(python3 -c 'import shlex,sys; print(shlex.quote(sys.argv[1]))' "${CLUTCH_INFISICAL_ENV}")"
  cat "${INTERNAL_TMP}"
} > "${ENV_FILE}"
chmod 600 "${ENV_FILE}"
rm -f "${INTERNAL_TMP}"
INTERNAL_TMP=""

cat > "${SOURCE_FILE}" <<EOF
# Source me: set -a; source "${ENV_FILE}"; set +a
if [ -f "${ENV_FILE}" ]; then
  set -a
  # shellcheck disable=SC1090
  . "${ENV_FILE}"
  set +a
fi
EOF
chmod 600 "${SOURCE_FILE}"

# 6.  Make the managed keys available in THIS process so a follow-up
#     command in the same agent step (e.g. `pnpm typecheck && pnpm test`)
#     sees them through initClutchSettings' env-seed path.
# shellcheck disable=SC1090
set -a; source "${ENV_FILE}"; set +a

log "Infisical backfill written to ${ENV_FILE} (mode 0600)"
log "${REPO_NAME} start complete"
