export {
  STATIC_DSH_MODELS,
  DSH_MINIMUM_ACP_VERSION,
  DSH_PROVIDER_ID,
  DSH_MINIMAX_PROVIDER_ID,
  DSH_PER_MODEL_EFFORT_LEVELS,
  DSH_PROVIDER_DEFAULT_EFFORT,
  DshModelNotOfferedError,
  classifyDshError,
  dshCredentialCandidates,
  dshEffortLevelsForModel,
  dshEngineStem,
  dshInstalledEffortLevels,
  dshLoginNote,
  dshModelIdFromOptionValue,
  dshCanonicalWireModelId,
  dshModelOptionValue,
  dshPerModelEffortLevels,
  dshProviderForModel,
  dshReasoningEffortValue,
  dshSameModel,
  dshSpawnArgs,
  dshSupport,
  dshVersionCompatibilityReason,
  matchAdvertisedDshModel,
  parseAdvertisedDshModels,
  resolveDshModelOption,
} from "./driver.ts";
export type { DshAdvertisedModel, DshModelMatch, DshResolvedModel } from "./driver.ts";
export { isDshEngineCli } from "./mcp-patch.ts";
